name: CD with Docker

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bad0request/time-bot
  TELEGRAM_TO: -1003170352623

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
    steps:
       # Уведомление о начале деплоя
      - name: Notify deploy start
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.TELEGRAM_TO }} 
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            🚀 Мега Деплой стартовал Епта
            📦 Rep: ${{ github.repository }}
            🔖 Image: ${{ env.IMAGE_NAME }}
            ⏰ Time: ${{ github.event.workflow_run.created_at }}
            📎 Workflow: ${{ github.event.workflow_run.name }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ${{ env.REGISTRY }} -u "${{ secrets.REGISTRY_LOGIN }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -f ./Dockerfile -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker images
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

          # Уведомление об успешном завершении
      - name: Notify deploy success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.TELEGRAM_TO }}
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            ✅ Деплой прошел заебись!
            📦 Repository: ${{ github.repository }}
            🐳 Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            🏷️ Tags: ${{ github.sha }}, latest
            ⏱️ Duration: ${{ job.status }} 
            🔗 Registry: ${{ env.REGISTRY }}

      # Уведомление о неудачном деплое
      - name: Notify deploy failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.TELEGRAM_TO }}
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            ❌ Деплой не сработал(
            📦 Repository: ${{ github.repository }}
            🐳 Image: ${{ env.IMAGE_NAME }}
            ⚠️ Check workflow for details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}