name: Container Health Check

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

env:
  TELEGRAM_TO: -1003170352623
  CONTAINER_NAME: "bot-ebal-nahui"

jobs:
  container-health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check container via SSH
        id: container-check
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            CONTAINER="${{ env.CONTAINER_NAME }}"
            # ... ваш скрипт проверки контейнера

      - name: Send Telegram report
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.TELEGRAM_TO }}
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            ОТЧЕТ О КОНТЕЙНЕРЕ
            
            Контейнер: ${{ env.CONTAINER_NAME }}
            Статус: ${{ steps.container-check.outputs.status }}
            Детали: ${{ steps.container-check.outputs.details }}
            
           