name: Daily Container Check

on:
  schedule:
    - cron: '2 * * * *'
  workflow_dispatch:

env:
  TELEGRAM_TO: -1003170352623
  CONTAINER_NAME: "bot-ebal-nahui"

jobs:
  container-health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check container via SSH
        id: container-check
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PRIVATE_KEY }} 
          script: 
            echo "✅ SSH connection successful!"