name: Test SSH Connection

on: 
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH
        id: ssh   # 👈 обязательно нужен id!
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "✅ SSH connection successful!"
            cat container_status.txt 2>/dev/null || echo "file_not_found"

      - name: Check if value was passed
        run: |
          echo "Raw stdout from SSH:"
          echo "${{ steps.ssh.outputs.stdout }}"
          # при необходимости можно доп.парсить stdout в bash

      - name: Debug SSH home
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "User: $(whoami)"
            echo "Home: $HOME"
            ls -la $HOME