on:
  workflow_run:
    workflows: ["CD with Docker"]       
    types: [completed]       
env:
  WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}
  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
  TELEGRAM_TO: -1003170352623

jobs:
  webhook-notify:        
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/webhook-notify
        id: webhook
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          token: ${{ secrets.WEBHOOK_TOKEN }}


      # УСПЕШНЫЙ WEBHOOK (200)
      - name: Notify webhook success
        if: steps.webhook.outputs.response_code == '200'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.TELEGRAM_TO }}
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            ✅ Webhook Successful!
            📡 Status: HTTP 200 OK
            💫 Deployment completed successfully
            🔗 Webhook: ${{ env.WEBHOOK_URL }}

      # ОШИБКИ КЛИЕНТА (400, 401, 403)
      - name: Notify webhook client error
        if: steps.webhook.outputs.response_code == '400' || steps.webhook.outputs.response_code == '401' || steps.webhook.outputs.response_code == '403'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.TELEGRAM_TO }}
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            ⚠️ Webhook Client Error
            📡 Status: HTTP ${{ steps.webhook.outputs.response_code }}
            🔍 Issue: 
            ${{ steps.webhook.outputs.response_code == '400' && 'Bad Request - Check webhook data' || '' }}
            ${{ steps.webhook.outputs.response_code == '401' && 'Unauthorized - Invalid token' || '' }}
            ${{ steps.webhook.outputs.response_code == '403' && 'Forbidden - Access denied' || '' }}
            🔗 Webhook: ${{ env.WEBHOOK_URL }}